// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbo2MYJjLgnsX7o1LIU3CEbbBr1Klgt4Q',
    appId: '1:825513133230:web:8f877d50390d7947bb993f',
    messagingSenderId: '825513133230',
    projectId: 'inventorycounter-f3f12',
    authDomain: 'inventorycounter-f3f12.firebaseapp.com',
    storageBucket: 'inventorycounter-f3f12.firebasestorage.app',
    measurementId: 'G-T7GSXZRDJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjFa3KdCMKJ-xuATqnf7U6gzpfBrpzLdc',
    appId: '1:825513133230:android:118d174a86e98406bb993f',
    messagingSenderId: '825513133230',
    projectId: 'inventorycounter-f3f12',
    storageBucket: 'inventorycounter-f3f12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmJl-CKU-3-gLz9j8_BxWgifiG2TdQC3w',
    appId: '1:825513133230:ios:7e7c3d86d85b1395bb993f',
    messagingSenderId: '825513133230',
    projectId: 'inventorycounter-f3f12',
    storageBucket: 'inventorycounter-f3f12.firebasestorage.app',
    iosBundleId: 'com.example.inventoryCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmJl-CKU-3-gLz9j8_BxWgifiG2TdQC3w',
    appId: '1:825513133230:ios:7e7c3d86d85b1395bb993f',
    messagingSenderId: '825513133230',
    projectId: 'inventorycounter-f3f12',
    storageBucket: 'inventorycounter-f3f12.firebasestorage.app',
    iosBundleId: 'com.example.inventoryCounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbo2MYJjLgnsX7o1LIU3CEbbBr1Klgt4Q',
    appId: '1:825513133230:web:2ed3da8983efbb73bb993f',
    messagingSenderId: '825513133230',
    projectId: 'inventorycounter-f3f12',
    authDomain: 'inventorycounter-f3f12.firebaseapp.com',
    storageBucket: 'inventorycounter-f3f12.firebasestorage.app',
    measurementId: 'G-EGET6G7Y51',
  );
}
